<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>net.slion</groupId>
        <artifactId>slion-modules</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>slion-job</artifactId>
    <packaging>jar</packaging>

    <description>
        slion-job 任务调度
    </description>

    <dependencies>
        <dependency>
            <groupId>net.slion</groupId>
            <artifactId>slion-common-json</artifactId>
        </dependency>
        <dependency>
            <groupId>net.slion</groupId>
            <artifactId>slion-common-job</artifactId>
        </dependency>
    </dependencies>

</project>
