<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.slion</groupId>
        <artifactId>slion-common</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>slion-common-sse</artifactId>

    <description>
        slion-common-sse 模块
    </description>

    <dependencies>
        <dependency>
            <groupId>net.slion</groupId>
            <artifactId>slion-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>net.slion</groupId>
            <artifactId>slion-common-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>net.slion</groupId>
            <artifactId>slion-common-satoken</artifactId>
        </dependency>
        <dependency>
            <groupId>net.slion</groupId>
            <artifactId>slion-common-json</artifactId>
        </dependency>
    </dependencies>

</project>
